Small fixes

diff --git a/drp b/drp
--- a/drp
+++ b/drp
@@ -22,7 +22,7 @@ FIXRATE=1
 RATELOCK="0.005"
 AUTOMAP=1
 MAPPER="$(dirname "$0")/smap"
-OUTDIR="~"
+OUTDIR="CHANGEME"
 
 # Best not to change the following settings unless you know what you're doing
 TEMPROOT="$OUTDIR/00DRP"
@@ -972,6 +972,11 @@ function process {
 IFS=$'\n'
 dryrun=0
 rundir="$(pwd)"
+
+if [ "$OUTDIR" == "CHANGEME" ]; then
+	echo "ERROR: You need to set OUTDIR to your output directory at the top of the script."
+	exit 1
+fi
 
 while getopts ":i:o:s:m:d:f:" flag; do
 	case "${flag}" in
diff --git a/smap b/smap
--- a/smap
+++ b/smap
@@ -1,5 +1,5 @@
 #!/bin/bash
-# smap (Segment Mapper) bash script - Dec. 8 2024
+# smap (Segment Mapper) bash script - Dec. 9 2024
 #
 # This script attempts to analyze an MKV file produced by MakeMKV from a DVD 
 # source and find where the original frame rates change in the video.  It
@@ -13,7 +13,7 @@ MINSEG="3"
 
 # Set directories if not exported from drp (i.e. if not running smap directly)
 if [ ! "$OUTDIR" ]; then
-	OUTDIR="~"
+	OUTDIR="CHANGEME"
 fi
 if [ ! "$TEMPROOT" ]; then
 	TEMPROOT="$OUTDIR/00DRP"
@@ -342,6 +342,11 @@ function makemap {
 
 IFS=$'\n'
 rundir="$(pwd)"
+
+if [ "$OUTDIR" == "CHANGEME" ]; then
+	echo "ERROR: You need to set OUTDIR to your output directory at the top of the script."
+	exit 1
+fi
 
 infile="$1"
 infilename="$(echo $infile |cut -d. -f1)"
